In [70]:
from torch.nn import Linear
import torch

In [76]:
m = Linear(20, 30)

In [77]:
input = torch.randn(128, 20)
# input = torch.arange(1, 129, dtype=torch.float32).view(1, 1, 128, 20)

In [78]:
input.shape

torch.Size([128, 20])

In [79]:
output = m(input)

In [80]:
output.shape

torch.Size([128, 30])

In [25]:
n = Linear((20, 20), (30, 30))

TypeError: new() received an invalid combination of arguments - got (tuple, tuple), but expected one of:
 * (torch.device device)
 * (torch.Storage storage)
 * (Tensor other)
 * (tuple of ints size, torch.device device)
      didn't match because some of the arguments have invalid types: (tuple, tuple)
 * (object data, torch.device device)
      didn't match because some of the arguments have invalid types: (tuple, tuple)


In [28]:
m.weight.shape

torch.Size([30, 20])

In [31]:
m.weight[:3, :2]

tensor([[-0.2232, -0.2100],
        [ 0.1469,  0.1339],
        [ 0.0510,  0.0526]], grad_fn=<SliceBackward>)

In [34]:
m.bias[:3]

tensor([-0.0998,  0.1883,  0.0515], grad_fn=<SliceBackward>)

In [38]:
from torch.nn import Upsample

In [65]:
input = torch.arange(1, 5, dtype=torch.float32).view(1, 1, 2, 2)

In [66]:
input

tensor([[[[1., 2.],
          [3., 4.]]]])

In [61]:
m = Upsample(scale_factor=2, mode='bilinear', align_corners=True)

In [62]:
m(input)

tensor([[[[1.0000, 1.3333, 1.6667, 2.0000],
          [1.6667, 2.0000, 2.3333, 2.6667],
          [2.3333, 2.6667, 3.0000, 3.3333],
          [3.0000, 3.3333, 3.6667, 4.0000]]]])

In [69]:
input.shape

torch.Size([1, 1, 2, 2])

In [67]:
from torch.nn import AdaptiveAvgPool2d
m = AdaptiveAvgPool2d((5,7))
# input = torch.randn(1, 64, 8, 9)
output = m(input)

In [68]:
output.shape

torch.Size([1, 1, 5, 7])